name: comp_neuro
channels:
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - asttokens=3.0.0
  - bzip2=1.0.8
  - ca-certificates=2025.1.31
  - colorama=0.4.6
  - comm=0.2.2
  - cpython=3.13.2
  - debugpy=1.8.12
  - decorator=5.1.1
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - expat=2.6.4
  - importlib-metadata=8.6.1
  - ipykernel=6.29.5
  - ipython=8.32.0
  - jedi=0.19.2
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - krb5=1.21.3
  - libffi=3.4.4
  - libmpdec=4.0.0
  - libsodium=1.0.20
  - matplotlib-inline=0.1.7
  - nest-asyncio=1.6.0
  - openssl=3.4.1
  - packaging=24.2
  - parso=0.8.4
  - pickleshare=0.7.5
  - pip=25.0
  - platformdirs=4.3.6
  - prompt-toolkit=3.0.50
  - psutil=6.1.1
  - pure_eval=0.2.3
  - pygments=2.19.1
  - python=3.13.2
  - python-dateutil=2.9.0.post0
  - python_abi=3.13
  - pywin32=307
  - pyzmq=26.2.1
  - setuptools=75.8.0
  - six=1.17.0
  - sqlite=3.45.3
  - stack_data=0.6.3
  - tk=8.6.14
  - tornado=6.4.2
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  - ucrt=10.0.22621.0
  - vc=14.42
  - vc14_runtime=14.42.34433
  - vs2015_runtime=14.42.34433
  - wcwidth=0.2.13
  - wheel=0.45.1
  - xz=5.6.4
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.2.13
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.11.16
      - aiosignal==1.3.2
      - annotated-types==0.7.0
      - attrs==25.3.0
      - certifi==2025.1.31
      - charset-normalizer==3.4.1
      - click==8.1.8
      - contourpy==1.3.1
      - cycler==0.12.1
      - datasets==3.5.0
      - dill==0.3.8
      - docker-pycreds==0.4.0
      - filelock==3.13.1
      - fonttools==4.56.0
      - frozenlist==1.5.0
      - fsspec==2024.6.1
      - gitdb==4.0.12
      - gitpython==3.1.44
      - huggingface-hub==0.30.1
      - idna==3.10
      - jaxtyping==0.2.38
      - jinja2==3.1.4
      - kiwisolver==1.4.8
      - markupsafe==2.1.5
      - matplotlib==3.10.0
      - mpmath==1.3.0
      - multidict==6.3.2
      - multiprocess==0.70.16
      - networkx==3.3
      - numpy==2.1.2
      - pandas==2.2.3
      - pillow==11.0.0
      - propcache==0.3.1
      - protobuf==5.29.3
      - pyarrow==19.0.1
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pyparsing==3.2.1
      - pytz==2025.1
      - pyyaml==6.0.2
      - regex==2024.11.6
      - requests==2.32.3
      - safetensors==0.5.3
      - scipy==1.15.2
      - seaborn==0.13.2
      - sentry-sdk==2.22.0
      - setproctitle==1.3.5
      - smmap==5.0.2
      - sympy==1.13.1
      - tokenizers==0.21.1
      - torch==2.6.0+cu126
      - torchaudio==2.6.0+cu126
      - torchvision==0.21.0+cu126
      - tqdm==4.67.1
      - transformers==4.50.3
      - typeguard==2.13.3
      - tzdata==2025.1
      - urllib3==2.3.0
      - wadler-lindig==0.1.3
      - wandb==0.19.7
      - xxhash==3.5.0
      - yarl==1.18.3
