group_name: "inhibition_dominance"

param_grid:
  k_I: [0.25, 0.5, 1.0, 2.0, 4.0, 8.0, 16.0]
  
input_params:
  probability_config:
    mixing_parameter: [0.2, 0.3, 0.4, 0.5, 0.6]
    location: [0.0]
    concentration: [0.5, 0.75, 1.0, 1.5, 2.0]