group_name: "initial_visualisation"

param_grid:
  repeats: [1]
  N_I: [50]
  homeostasis: [True, False] 

input_params:
  probability_config:
    mixing_parameter: [0.4]
    location: [0.0]
    concentration: [1.0]