group_name: "input_density_modulation"

param_grid:
  repeats: [4]
  homeostasis: [True, False]
  activation_function_name: ["rectified_linear", "rectified_power_law_1p5", "rectified_quadratic", "rectified_cubic"]

input_params:
  density_config:
    mixing_parameter: [0.2, 0.3, 0.4, 0.5, 0.6]
    location: [0.0]
    concentration: [0.5, 0.75, 1.0, 1.5, 2.0]