group_name: "test"

param_grid:
  repeats: [1]
  T: [50]
  N_I: [100]
  N_E: [100]
  homeostasis: [True] 

input_params:
  input_generator_name: "torus_input_generator"
  inhibitory_third_factor_config:
    mixing_parameter: [0.2, 0.4, 0.6]
    location: [[0.0, 0.0]]
    concentration: [1.0]