group_name: "time_scale_ratio"

param_grid:
  tau_product: [4.0]
  T: [2000.0]
  tau_W: [0.125, 0.25, 0.5, 1.0, 2.0, 4.0, 8.0]
  tau_k: [16.0]
  
input_params:
  probability_config:
    mixing_parameter: [0.2, 0.3, 0.4, 0.5, 0.6]
    location: [0.0]
    concentration: [0.5, 0.75, 1.0, 1.5, 2.0]