group_name: "width_power_law"

param_grid:
  homeostasis_power: [1.0, 1.33333, 2.0, 4.0]

input_params:
  width_config:
    mixing_parameter: [0.2, 0.3, 0.4, 0.5, 0.6]
    location: [0.0]
    concentration: [0.5, 0.75, 1.0, 1.5, 2.0]