group_name: "deterministic_sweep"

base_params:
  target_rate: 1.0
  num_latents: 200
  N_E: 100
  N_I: 50
  wandb_logging: True
  random_seed: 42
  covariance_learning: False
  activation_function_name: "rectified_quadratic"
  initial_feedforward_weight_scaling: 0.1
  dt: 0.1
  tau_u: 50.0
  tau_M: 1000.0
  tau_W: 2000.0
  tau_k: 2000.0
  zeta: 10.0
  T: 2500000.0 
  k_I: 20.0
  rate_homeostasis: True
  dynamics_log_time: 1000.0
  mode_log_time: 1000.0

param_grid:
  variable_input_mass: [True, False]
  activation_function_name: ["rectified_linear", "rectified_powerlaw_1p5", "rectified_quadratic"]

  input_config:
    - type: "circular" 
      param_grid:  
        mixing_parameter: [0.1, 0.25, 0.5]
        vm_concentration: [1.0]
        tuning_width: [0.25] 